name: Weekly Build
on:
  workflow_dispatch:
  #Intentionally switched off schedule 
  #schedule: 
  #  - cron: "0 0 * * 1"  

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      #Checkout
      - uses: actions/checkout@v2
        with:
          lfs: true

      # Restore Test Cache
      - uses: actions/cache@v3
        with:
          path: Unity CI CD/Library
          key: Library-Test
          restore-keys: |
            Library-

      # Test
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: "Unity CI CD"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: EditMode

      # Upload Test Results
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts

  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      releaseNotes: ${{ steps.tag_version.outputs.changelog }}
      tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Restore Build Cache
      - uses: actions/cache@v3
        with:
          path: Unity CI CD/Library
          key: Library-Build
          restore-keys: |
            Library-

      # Tag
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main

      # Build
      - uses: game-ci/unity-builder@v2
        env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
            projectPath: "Unity CI CD"
            buildsPath: "build"
            versioning: Custom
            version: ${{ steps.tag_version.outputs.new_tag }}
            targetPlatform: Android

      # Use Cache to transfer build result between jobs
      - uses: actions/cache/save@v3
        id: cache
        with:
          path: build/Android/*.apk
          key: Build-output-${{ steps.tag_version.outputs.new_tag }}    

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:

      # Restore Build From Cache
      - uses: actions/cache@v3
        with:
          enableCrossOsArchive: true
          path: build/Android/*.apk
          key: Build-output-${{ needs.build.outputs.tag }}
          restore-keys: |
            Build-output-${{ needs.build.outputs.tag }}

      # Create Release
      - uses: ncipollo/release-action@v1
        with:
          body: ${{ needs.build.outputs.releaseNotes }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ needs.build.outputs.tag }}
          name: Release ${{ needs.build.outputs.tag }}
          artifacts: "build/Android/*.apk"