name: Weekly Build
on:
  workflow_dispatch:
  schedule: 
    - cron: "0 0 * * 1"  

jobs:
  testAllModes:
    name: Build
    runs-on: ubuntu-latest
    steps:

      #Checkout
      - uses: actions/checkout@v2
        with:
          lfs: true

      # Test
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: "Unity CI CD"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: EditMode

      # Upload Test Results
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts

      # Tag
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main

      # Build
      - uses: game-ci/unity-builder@v2
        env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
            projectPath: "Unity CI CD"
            buildsPath: "build"
            versioning: Custom
            version: ${{ steps.tag_version.outputs.new_tag }}
            targetPlatform: Android

      # Create Release
      - uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.tag_version.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          artifacts: "build/*"