name: Test project

#Run on all pull requests that contain script, json or yaml changes
on: 
  pull_request:
    paths:
      - '**.cs'
      - '**.yml'
      - '**.json'

jobs:
  testAllModes:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          lfs: true

      # Restore Cache
      - uses: actions/cache@v3
        with:
          path: Unity CI CD/Library
          key: Library-Test
          restore-keys: |
            Library-

      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: "Unity CI CD"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: EditMode

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts